### ISSUE TITLE
webpack.config.js not getting picked up properly

### ISSUE THREAD

**Issue by mflodin** [TheLarkInn/webpack-workshop-2018#18]
I'm experiencing an issue where webpack.config.js is not being picked up when running `npm run webpack` (or `yarn webpack`) in the branch _03-fem-debug-script_. Seems to be caused by both `webpack-cli` and `webpack-command` being installed. Removing `webpack-command` and then doing `npm install` seems to fix the issue.

I have not completed the full course yet, so not sure if `webpack-command` is used in anyway later, but otherwise I would suggest to remove it.

**Comment by romariolopezc** [comment]
I'm also getting this issue in _031-all-module-types_

**Comment by 1Marc** [comment]
I don't think @TheLarkInn uses `webpack-command` at all in any of the courses... I just DM'd him to ask if I can remove this from the package.json in all the branches.

**Comment by 1Marc** [comment]
Ok, I went and removed `webpack-command` from all package.json's I could find.
