### ISSUE TITLE
Production build is throwing webpack error

### ISSUE THREAD

**Issue by bhupendra1011** [TheLarkInn/webpack-workshop-2018#19]
I have same package.json and webpack.config.js file as in Branch : **feature/04010-composing-configs-webpack-merge**

but when I run yarn prod I get below error 
`✖ ｢webpack｣: Flags were specified that were not recognized:
  --env  Not sure what you mean there
Please check the command executed.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webpack-workshop-2018@1.0.0 webpack: `webpack "--env.mode" "production"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webpack-workshop-2018@1.0.0 webpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be foundin:
`
Please find attachment for detailed log of ther error.
However development build {yarn dev} works fine.
[2018-07-10T10_25_47_813Z-debug.log](https://github.com/TheLarkInn/webpack-workshop-2018/files/2179955/2018-07-10T10_25_47_813Z-debug.log)

**Comment by jacobedawson** [comment]
Getting the same error running npm run prod:

```
× ｢webpack｣: Flags were specified that were not recognized:

  --env  Not sure what you mean there
```

**Comment by 1Marc** [comment]
Potentially related to #18 ? I fixed that. I just tried 
```bash
git checkout feature/04010-composing-configs-webpack-merge -f
npm install
npm run prod
```

And it seemed to work for me...

**Comment by 1Marc** [comment]
Any updates on this @bhupendra1011 and @jacobedawson ?

**Comment by bhupendra1011** [comment]
@1Marc  prod build working fine now . Thanks 👍
