### ISSUE TITLE
Loading multiple presets

### ISSUE THREAD

**Issue by gabberr** [TheLarkInn/webpack-workshop-2018#30]
In the loading presets lesson, the typescript preset is loaded like this:

`npm run prod --env.presets typescript`

In case there are multiple presets available and I want to load some of them, how to pass the presets?

For example `npm run prod --env.presets typescript compression` does not work.

Thank you for the awesome webpack lessons!

**Comment by TheLarkInn** [comment]
Sorry I just noticed this perhaps this is a bug If you see a fix, by all means submit a PR and I'll try and update my branches.

**Comment by gabberr** [comment]
Hello, thanks for the reply. 

I found the answer on this website called webpack.js.org docs(Who would have thought, right): https://webpack.js.org/api/cli/#environment-options.

To pass multiple preset values, we reuse the same  'key' :
`npm run prod --env.presets typescript --env.presets compression`

This way you get in the env `{presets: [ "typescript", "compression" ]}`
