### ISSUE TITLE
Uncaught TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by idrismakesgames** [TheLarkInn/webpack-workshop-2018#33]
I thought I made a mistake so I wiped my folder and cloned this repo again, switch to branch feature/0312-webpack-dev-server ran yarn install and then ran yarn dev.

no errors in the terminal, but on the page in the console nothing is happening and the following error appears.

`Uncaught TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (index.js:20)
    at eval (index.js:2)
    at Object../src/index.js (index.js:357)
    at __webpack_require__ (index.js:20)
    at eval (webpack:///multi_(:8080/webpack)-dev-server/client?:2:18)
    at Object.0 (index.js:368)
    at __webpack_require__ (index.js:20)
    at index.js:69
    at index.js:72`

Really hope you can help, as I desperately want to follow along, so far this course has been a life saver.

**Comment by notdrone** [comment]
removing all  `^` from the package.json file and then doing `npm i` fixed the error for me.

**Comment by sidouglas** [comment]
Course was published June 29, 2018, and it's typical with webpack is fickle, and this the course no longer works.
( I ran into the exact same thing this evening )

I did:

```
yarn upgrade-interactive
```
Check everything - upgrade everything and re-run the dev server.

**Comment by 1Marc** [comment]
I will have to upgrade and test out all of the branches at some point -- thanks all for pointing me in the right direction.

**Comment by sojungko** [comment]
Had the same issue. Upgrading `webpack` and `webpack-dev-server` fixed it for me.

```
    "webpack": "^4.33.0",
    "webpack-dev-server": "^3.7.1",
```

**Comment by 1Marc** [comment]
Sorry for the delay, but the dependencies for the `feature/0312-webpack-dev-server` branch have been updated! https://github.com/TheLarkInn/webpack-workshop-2018/commit/9a7defb6494ab747ff72a2068e6f9551b63f8aa8
